sankey-beta
    URL Queue, Scraper, 1000
    Scraper, Valid HTML, 950
    Scraper, Network Error, 50
    Valid HTML, Parser, 950
    Parser, JSON Entity, 940
    Parser, Parse Error, 10
    JSON Entity, Storage, 940
