gantt
    title Historical Backfill Schedule
    dateFormat  YYYY-MM-DD
    section Setup
    Init Project :done, des1, 2023-10-01, 2d
    section 2020 Data
    Jan-Jun 2020 :active, a1, 2023-10-03, 5d
    Jul-Dec 2020 :after a1, 5d
    section 2021 Data
    Jan-Dec 2021 :2023-10-13, 10d
