mindmap
  root((Mexican Law))
    Constitution
      Political Constitution
    Federal
      Federal Laws
      Federal Codes
      Regulations
    State
      State Constitutions
      State Codes
      Municipal Regulations
    International
      Treaties
      Agreements
